<x-app-layout page-title="Home |">

    {{-- <div x-data="{
        currentPage: 1,
        itemsPerPage: 5,
        maxPagesToShow: 3, // Maximum number of paginator buttons to show around the current page button
        items: [
            { id: 1, name: 'Item 1' },
            { id: 2, name: 'Item 2' },
            { id: 3, name: 'Item 3' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 25, name: 'Item 60' }
        ]
    }">
    <button x-on:click="currentPage = Math.max(currentPage - 1, 1)">Previous</button>
    <div class="paginator">
        <template x-for="page in Math.min(Math.ceil(items.length / itemsPerPage), maxPagesToShow * 2 + 1)" :key="page">
            <template x-if="page === 1 || page === Math.ceil(items.length / itemsPerPage) || (page >= currentPage - maxPagesToShow && page <= currentPage + maxPagesToShow)">
                <button x-on:click="currentPage = page" x-text="page" x-bind:class="{ 'underline': currentPage === page }"></button>
            </template>
        </template>
    </div>
    <button x-on:click="currentPage++" x-bind:disabled="currentPage >= Math.ceil(items.length / itemsPerPage)">Next</button>

    <div>
        Page <span x-text="currentPage"></span> of <span x-text="Math.ceil(items.length / itemsPerPage)"></span>
    </div>

    <template x-for="(item, index) in items.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage)" :key="index">
        <div x-text="item.name"></div>
    </template>
    </div> --}}

    <div x-data="{
        currentPage: 1,
        itemsPerPage: 5,
        maxPagesAroundCurrentPage: 2, // Maximum number of paginator buttons to show around the current page button
        items: [
            { id: 1, name: 'Item 1' },
            { id: 2, name: 'Item 2' },
            { id: 3, name: 'Item 3' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 1, name: 'Item 1' },
            { id: 2, name: 'Item 2' },
            { id: 3, name: 'Item 3' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 25, name: 'Item 594' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 1, name: 'Item 1' },
            { id: 2, name: 'Item 2' },
            { id: 3, name: 'Item 3' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 25, name: 'Item 594' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 1, name: 'Item 1' },
            { id: 2, name: 'Item 2' },
            { id: 3, name: 'Item 3' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 25, name: 'Item 594' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 1, name: 'Item 1' },
            { id: 2, name: 'Item 2' },
            { id: 3, name: 'Item 3' },
            { id: 4, name: 'Item 4' },
            { id: 5, name: 'Item 5' },
            { id: 6, name: 'Item 6' },
            { id: 7, name: 'Item 7' },
            { id: 8, name: 'Item 8' },
            { id: 9, name: 'Item 9' },
            { id: 10, name: 'Item 10' },
            { id: 11, name: 'Item 11' },
            { id: 12, name: 'Item 12' },
            { id: 13, name: 'Item 13' },
            { id: 14, name: 'Item 14' },
            { id: 15, name: 'Item 15' },
            { id: 16, name: 'Item 16' },
            { id: 17, name: 'Item 17' },
            { id: 18, name: 'Item 18' },
            { id: 19, name: 'Item 19' },
            { id: 20, name: 'Item 20' },
            { id: 21, name: 'Item 21' },
            { id: 22, name: 'Item 22' },
            { id: 23, name: 'Item 23' },
            { id: 24, name: 'Item 24' },
            { id: 24, name: 'Item 25' },
            { id: 24, name: 'Item 26' },
            { id: 24, name: 'Item 27' },
            { id: 24, name: 'Item 28' },
            { id: 24, name: 'Item 29' },
            { id: 24, name: 'Item 30' },
            { id: 24, name: 'Item 31' },
            { id: 24, name: 'Item 32' },
            { id: 24, name: 'Item 33' },
            { id: 24, name: 'Item 34' },
            { id: 24, name: 'Item 35' },
            { id: 24, name: 'Item 36' },
            { id: 24, name: 'Item 37' },
            { id: 24, name: 'Item 38' },
            { id: 24, name: 'Item 39' },
            { id: 24, name: 'Item 40' },
            { id: 24, name: 'Item 41' },
            { id: 24, name: 'Item 42' },
            { id: 24, name: 'Item 43' },
            { id: 24, name: 'Item 44' },
            { id: 24, name: 'Item 45' },
            { id: 24, name: 'Item 46' },
            { id: 24, name: 'Item 47' },
            { id: 24, name: 'Item 48' },
            { id: 24, name: 'Item 49' },
            { id: 24, name: 'Item 50' },
            { id: 24, name: 'Item 51' },
            { id: 24, name: 'Item 52' },
            { id: 24, name: 'Item 53' },
            { id: 24, name: 'Item 54' },
            { id: 24, name: 'Item 55' },
            { id: 24, name: 'Item 56' },
            { id: 24, name: 'Item 57' },
            { id: 24, name: 'Item 58' },
            { id: 25, name: 'Item 59' },
            { id: 25, name: 'Item 594' },
            { id: 25, name: 'Item 60' }
        ]
    }">
        
        <div class="inline-flex -space-x-px">
            <button class="h-8 ml-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg w-9 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" x-on:click="currentPage = 1"><<</button>
            <button class="h-8 leading-tight text-gray-500 bg-white border border-gray-300 w-9 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" x-on:click="currentPage = Math.max(currentPage - 1, 1)"><</button>
            <template x-for="page in Math.ceil(items.length / itemsPerPage)" :key="page">
                <button class="h-8 leading-tight text-gray-500 bg-white border border-gray-300 w-9 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" x-on:click="currentPage = page" x-text="page" x-bind:class="{ '!border-red-500': currentPage === page }" x-show="currentPage + 1"></button>
            </template>
            <button class="h-8 leading-tight text-gray-500 bg-white border border-gray-300 w-9 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" x-on:click="currentPage++" x-bind:disabled="currentPage >= Math.ceil(items.length / itemsPerPage)">></button>
            <button class="h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg w-9 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" x-on:click="currentPage = Math.ceil(items.length / itemsPerPage)">>></button>
        </div>
    
        <div>
            Page <span x-text="currentPage"></span> of <span x-text="Math.ceil(items.length / itemsPerPage)"></span>
        </div>
    
        <template x-for="(item, index) in items.slice((currentPage - 1) * itemsPerPage, currentPage * itemsPerPage)" :key="index">
            <div x-text="item.name"></div>
        </template>




    </div>


    {{-- <div x-data="{ number: 13 }">
        <button @click="number--; number = Math.max(number, 1)">-</button>
        <span x-text="number"></span>
        <button @click="number++; number = Math.min(number, 25)">+</button>
        <ul>
            <template x-for="n in [-2, -1, 0, 1, 2]" :key="n">
                <button x-on:click="number = n" x-text="number + n" x-show="number + n >= 1 && number + n <= 25" x-bind:class="{ 'underline': number === n }"></button>
                <li x-text="number + n" x-show="number + n >= 1 && number + n <= 25"></li>
            </template>
        </ul>
    </div> --}}


    
  
    
    
    
    
    
    
    
    

    
    
    
    
    
    
    
</x-app-layout>